### ISSUE TITLE
jsonDecodingError when downloading binaries

### ISSUE THREAD

**Issue by NachoSoto** [Carthage/Carthage#2157]
* `carthage version`: 0.25.0
* `xcodebuild -version`: Xcode 9.0
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

`carthage checkout`

**Carthage Output**
```
*** Skipped installing ReactiveSwift.framework binary due to the error:
	"GitHub API request failed: jsonDecodingError(Multiple(TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null)))"
*** Checking out ReactiveSwift at "2.0.1"
```

Probably something changed in GitHub's API?

**Comment by ikesyo** [comment]
I can't reproduce it. Does that still happen?

**Comment by ikesyo** [comment]
And also ReactiveSwift 2.0.1 doesn't have an attached binary.

https://github.com/ReactiveCocoa/ReactiveSwift/releases/tag/2.0.1

**Comment by ikesyo** [comment]
Closing this for now.

**Comment by methodiva** [comment]
happening to me when installing ```
github "nuclearace/Starscream" ~> 8.0.7
github "socketio/socket.io-client-swift" ~> 12.0.0
``` with `carthage update --platform ios`

**Comment by mxcl** [comment]
I've been gettin this for all qualifying binary downloads, which is a problem for Sentry since they only recommend you use the binary.

**Comment by mxcl** [comment]
Shall I open a new ticket, or you want to reopen?

**Comment by ikesyo** [comment]
Looks like the error is coming from here: https://github.com/mdiep/Tentacle/blob/682ef58707d347cb300c715821647c35c7b79231/Sources/Tentacle/Client.swift#L211-L217 and you should be hitting API rate limit.

**Comment by mxcl** [comment]
Or possibly some other auth issue, how does Carthage auth? ssh key I would have thought?

**Comment by ikesyo** [comment]
The root cause for the wired behavior is [a serious bug in Tentacle](https://github.com/mdiep/Tentacle/blob/682ef58707d347cb300c715821647c35c7b79231/Sources/Tentacle/Client.swift#L200-L205) and that is fixed in `master` by [this commit](https://github.com/mdiep/Tentacle/pull/87/commits/dc0d08b1195985cfc3f75ae6874176014b7b5b51). We should update Tentacle.

**Comment by ikesyo** [comment]
Submitted #2182.

**Comment by NachoSoto** [comment]
Ouch

**Comment by d4r1091** [comment]
Hey guys, following this thread as I haven't solved the issue yet...
🤔  thoughts? 💭 
I'm getting still getting this:
**Carthage 0.25.0**
```
*** Skipped installing MagicalRecord.framework binary due to the error:
	"GitHub API request failed: jsonDecodingError(Multiple(TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null)))"
*** Checking out MagicalRecord at "v2.3.3"
*** Skipped installing Facebook-ios-sdk.framework binary due to the error:
	"GitHub API request failed: jsonDecodingError(Multiple(TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null)))"
*** Checking out Facebook-ios-sdk at "sdk-version-4.21.0"
*** Skipped installing Bolts-ObjC.framework binary due to the error:
	"GitHub API request failed: jsonDecodingError(Multiple(TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null)))"
*** Checking out Bolts-ObjC at "1.8.4"
*** Skipped installing SDWebImage.framework binary due to the error:
	"GitHub API request failed: jsonDecodingError(Multiple(TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null)))"
*** Checking out SDWebImage at "3.8.2"
*** Skipped installing Charts.framework binary due to the error:
	"GitHub API request failed: jsonDecodingError(Multiple(TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null)))"
*** Checking out Charts at "v3.0.2"
*** Skipped installing intercom-ios.framework binary due to the error:
	"GitHub API request failed: jsonDecodingError(Multiple(TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null)))"
```

**Comment by ikesyo** [comment]
This is fixed in master but not released yet.

**Comment by ikesyo** [comment]
0.26 has been released.

https://github.com/Carthage/Carthage/releases/tag/0.26.0
