### ISSUE TITLE
Carthage 0.7.1 asking for GitHub username/pass for public repos

### ISSUE THREAD

**Issue by tonyarnold** [Carthage/Carthage#447]
Here is my Cartfile:

```
github "Thomvis/BrightFutures" "master"
github "ReactiveCocoa/ReactiveCocoa" "v3.0-beta.4"
```

Cartfile.private

```
github "quick/Quick" "master"
github "quick/Nimble" "master"
```

Cartfile.resolved

```
github "robrix/Box" "1.2.2"
github "Thomvis/BrightFutures" "ab20c2b5a9af958ebaccaf5f0d036441cdfe4f51"
github "quick/Nimble" "0aafb4fc24d1d4912af6caf0411e96bb43747218"
github "quick/Quick" "f614fdfd6d88de9b456fb479e5ec495791a69d11"
github "antitypical/Result" "0.4.1"
github "ReactiveCocoa/ReactiveCocoa" "1c8b18751c4af1f3c6003077ff57bed80e184c3a"
```

Anytime I try to update or bootstrap, I get:

```
~ ❯❯❯ carthage bootstrap --platform iOS
Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': 
```

**Comment by larryonoff** [comment]
I have the same issue.

**Comment by Devaria** [comment]
I see the same issue.

**Comment by Devaria** [comment]
Adding to this using 'carthage update --use-ssh' still gives me a prompt for Username for 'https://github.com'. Is the '--use-ssh' option ignored?

**Comment by elliottsj** [comment]
Here's my workaround for now:

1. Install and enable the [git caching credential helper](https://help.github.com/articles/caching-your-github-password-in-git/).
2. **If you use 2-factor authentication:** Create a [personal access token](https://github.com/settings/tokens), copy it to your clipboard.
3. Attempt a `git push` to any GitHub HTTPS remote. Git will ask for your GitHub username & password; **if using 2FA, paste your personal access token as the password**.

    Regardless of whether or not the push succeeded, your password/access token should now be cached on your machine.
4. Now try `carthage update`; when Carthage fetches from GitHub, it should use your cached password/access token.

**Comment by jspahrsummers** [comment]
I agree this is a serious bug in Carthage, and I apologize to everyone experiencing it!

Unfortunately, I'll be unavailable for a few days (bad timing). If nobody else in @Carthage/carthage is around to apply a fix, I'd recommend that anyone affected download and install [0.7](https://github.com/Carthage/Carthage/releases/tag/0.7) or [0.6.5](https://github.com/Carthage/Carthage/releases/tag/0.6.5) until we can create a proper fix.

Sorry again about the trouble! :heart:

**Comment by tonyarnold** [comment]
No stress, JSpah — enjoy your time off (?) :wave:

**Comment by mdiep** [comment]
0.7.2 was released, which should fix this issue for anyone using Xcode 6.3+.

**Comment by tonyarnold** [comment]
Sorry @mdiep 0.7.2 still has the same hanging behaviour as 0.7.1 for me :(

```
❯❯❯ carthage bootstrap --platform iOS
*** No Cartfile.resolved found, updating dependencies
*** Cloning Nimble
*** Cloning Quick
*** Cloning Bond
*** Cloning BrightFutures
```

It's been sitting there for 30 minutes.

**Comment by tonyarnold** [comment]
Here's a spin dump of carthage in this state: https://dl.dropboxusercontent.com/u/153352/Sample%20of%20carthage.zip

**Comment by mdiep** [comment]
@tonyarnold What's the output of `git --version` and `xcodebuild -version`?

**Comment by tonyarnold** [comment]
```
~ ❯❯❯ git --version                                                                                                                                                                       ⏎
git version 2.4.0
~ ❯❯❯ xcodebuild -version
Xcode 6.4
Build version 6E23
```

**Comment by robrix** [comment]
Was this fixed by 0.7.2 or 0.7.3?

**Comment by fonkadelic** [comment]
@robrix v0.7.3 has fixed the problem for me

**Comment by fonkadelic** [comment]
Just to be clear... v0.7.3 fixed the issue about asking for GitHub user / password... not the hanging behaviour @tonyarnold described above

**Comment by mdiep** [comment]
I believe the remaining hanging issue is captured by #445.

**Comment by exsortis** [comment]
I just updated to 0.7.3, and I'm still experiencing the username/password issue.

**Comment by mdiep** [comment]
@exsortis What's the output of `git --version` and `xcodebuild -version`?

**Comment by exsortis** [comment]
```
🍔  xcodebuild -version
Xcode 6.3.1
Build version 6D1002
```

```
🍔  git --version
git version 2.4.0
```

**Comment by guidomb** [comment]
I have the same versions as @exsortis and Carthage `0.7.3` fix the issue related with asking Github credentials.

**Comment by yoiang** [comment]
@mdiep I am also still experiencing the username/password prompt with
```
$ xcodebuild -version
Xcode 6.3.2
Build version 6D2105

$ git --version
git version 2.4.0
```

**Comment by jspahrsummers** [comment]
If you have _never_ provided username/password for HTTPS (or SSH key passphrase), and you're trying to clone a _private_ repository, you will see a prompt.

See https://github.com/Carthage/Carthage/issues/219.

**Comment by yoiang** [comment]
@jspahrsummers I feel the fool, I had a typo in the name of a newly added repo. There probably isn't any way for Carthage to know whether a `github` specification is a private repo or doesn't actually exist, huh. 

Perhaps before prompting for a username/password for HTTPS Carthage could prompt the user that they should only be prompted for private repos and if this is in error to double check his/her spelling?

**Comment by jspahrsummers** [comment]
Using private repositories is pretty common, in my experience, so I wouldn't want to see a prompt for all of those cases.

I think we should ideally just fix #219, so filling in the username and password will result in a more meaningful error message.

**Comment by bliang** [comment]
I got this working by caching my github credentials in the OSXKeychain... Follow instructions here: https://help.github.com/articles/caching-your-github-password-in-git/ and when prompted, allow it.

This will work with the bug that Carthage has for 0.8

**Comment by samskiter** [comment]
I just had this issue and used the solution @elliottsj posted

**Comment by Rupert-RR** [comment]
I just had this problem and solved it by updating git from 2.2.1 (to 2.5.something) — I suspect that this might have been caused by my re-installing Xcode 6.4 over the weekend to do a pre-Swift 2 build, then moving back to Xcode 7).

**Comment by samskiter** [comment]
Thanks @Rupert-RR - updating git fixed my problem

**Comment by ChaosCoder** [comment]
Mine, too. Thank @Rupert-RR

**Comment by mt81** [comment]
I have upgraded git to the last version ```brew upgrade git```

**Comment by virl** [comment]
Same issue with Carthage 0.29.0 and Git 2.18.0
